controllers:
    resource: ../src/Controller/
    type: attribute
index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        path: /login
        permanent: true